# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# .pre-commit-config.yaml

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        exclude: \.clang-format$  # Skip .clang-format files


- repo: local
  hooks:
    - id: format-py
      name: Run format.py
      entry: python3 scripts/format.py --fix --noconfirm
      exclude: \.pre-commit-config.yaml$
      language: python
      stages: [pre-commit]
